USE mydb;
SHOW TABLES;
SELECT * FROM employee;

DELIMITER $$
CREATE TRIGGER stop_del
BEFORE DELETE ON employee FOR EACH ROW
BEGIN
	SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = "You Can Not Delete an Employee";
END $$ DELIMITER ;
DELETE FROM employee WHERE eid=102;

SHOW TRIGGERS;
DELIMITER $$
CREATE TRIGGER before_ins
BEFORE INSERT ON employee FOR EACH ROW
BEGIN
	IF NEW.esal<30000 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = "Salary Should be above 30000";
	END IF;
END $$ DELIMITER ;

SELECT * FROM employee;
SELECT * FROM emp_log;
INSERT INTO employee VALUE(101,'Raman',"Noida",15000);

